config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "splashes/index"

  resources :categories
  resources :expenses
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  unauthenticated do
    root "splashes#index"
  end

  authenticated do
    root "categories#index", as: :authenticated_root
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  belongs_to :category, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def after_sign_up_path_for(_resource)
    categories_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:public]

  def index
    @categories = Category.where(user_id: current_user.id)
  end

  def show
    @expenses = Expense.all.where(category_id: @category.id)
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def new
    @expense = Expense.new
    @categories = Category.all.where(user_id: current_user.id)
  end

  def create
    @expense = Expense.create(expense_params)
    @expense.user_id = current_user.id
    respond_to do |format|
      if @expense.save
        format.html do
          redirect_to category_url(Category.find(@expense.category_id)), notice: 'Expense was successfully created.'
        end
      else
        @categories = Category.where(user_id: current_user.id).to_a
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :category_id)
  end
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def total_amount_helper(expenses)
    expenses.reduce(0) { |sum, expense| sum + expense.amount }
  end
end

app/views/categories/_category.html.erb
<div class="row card m-3 ps-1 pe-3 rounded">
  <div class="col-sm-4 m-0 p-0 d-flex align-items-center justify-content-center w-100">
    <p class=""> <%= image_tag category.icon, class:"category-img"%></p>
  </div>
  <div class="col-sm-8 d-flex justify-content-between w-100 m-0 p-0">      
    <ul class="d-flex flex-column align-items-center justify-content-start">
      <li> <div class="h4 py-2"><%= link_to category.name, category_path(category) %></div></li>
      <li> <p> <%= category.created_at.strftime("%d-%b-%Y")%></p></li>
    </ul>
    <ul class="d-flex flex-column justify-content-start m-0 p-0">
      <li><p class="py-2 text-center fw-bold"> $<%= total_amount_helper(Expense.all.where(category_id:category.id)) %></p></li>      
    </ul>
  </div>
</div>  

 
  

app/views/categories/_form.html.erb
<div class="header d-flex align-items-center justify-content-between px-4">
    <div>
        <%= link_to image_tag("https://img.icons8.com/ultraviolet/344/long-arrow-left.png"), root_path, class: "back_btn" %>
    </div>
    <h4 class="text-white">Add a category</h4>      
</div>

<div>
    <%= form_with(model: category) do |f| %>     
        <div class="text-center">
          <div class="my-3 px-3">
            <%= f.text_field :name, placeholder: "Category Name", require: true, class: 'w-100 bg-gray-100 p-2' %>
          </div>
          <div class="my-3 px-3">
              <%= f.select :icon, {"🛒 General Items" => "https://cdn-icons-png.flaticon.com/512/891/891462.png", "🎮 Electronics" =>"https://cdn-icons-png.flaticon.com/512/808/808439.png", "🚌 Transportation" => "https://cdn-icons-png.flaticon.com/512/1034/1034795.png","💄 Daily Consumables"=>"https://img.icons8.com/external-wanicon-flat-wanicon/344/external-make-up-beauty-cosmetics-wanicon-flat-wanicon.png"}, {}, class: 'w-100 bg-gray-100 p-2' %>
           </div>
           <div class="form-group">  
              <%= f.submit "Submit", class: "btn main-color" %>
           </div>
        </div>
    <% end %>
</div>

app/views/categories/index.html.erb
<section class="text-center vh-100">
    <div class="header d-flex align-items-center justify-content-between px-4">
        <div>
            <%= render "shared/navbar" %>
        </div>
        <div>
          <% if user_signed_in? %>
             <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn main-color" %>
          <% end %>
        </div>
    </div>


    <% if flash.notice %>
        <p class="notice"><%= notice %></p>
    <% end %>

    <div class="">
        <% if @categories.any?%>
            <% @categories.each do |category| %>
                <%= render category %>
            <% end %>
        <% else %>
            <p class="p-2 m-2 h3">There is no category added!!!</p>
        <% end %>
    </div>

    <div class="footer fixed-bottom py-4">
    <h4 class="text-white"><%= link_to "Add a category", new_category_path, class: "text-whites" %></h4>

    </div>

</section>

app/views/categories/new.html.erb
<section class="text-center vh-100">    
        <%= render "form", category: @category %>

        <div class="footer fixed-bottom py-4">        
        <% if user_signed_in? %> 
           <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn main-color" %>
        <% end %>
    </div>
</section>

app/views/categories/show.html.erb
<section class="text-center vh-100">
    <div class="header d-flex align-items-center justify-content-between px-4">
    <div>
        <%= link_to image_tag("https://img.icons8.com/ultraviolet/344/long-arrow-left.png"), root_path, class: "back_btn" %>
    </div>
        <h4 class="text-white">Transactions</h4>
    </div>

    <% if flash[:notice] %>
        <p class="notice" role="alert"><%= notice %></p>
    <% end %>
    <%= render @category %>
    <% @expenses.each do |expense| %>
        <div class="card m-3 rounded">
            <div class="h4 py-2"><%= expense.name.capitalize %></div>
            <p>$<%= expense.amount %></p>
        </div>
    <% end %>

    <div class="footer fixed-bottom py-4">        
        <%= link_to "Add Expense", new_expense_path, class: "btn main-color" %>        
        <% if user_signed_in? %> 
           <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn main-color" %>
        <% end %>
    </div>
</section>

app/views/expenses/new.html.erb
<section class="text-center vh-100">
  <div class="header d-flex align-items-center justify-content-between px-4">
    <div>
      <%= link_to image_tag("https://img.icons8.com/ultraviolet/344/long-arrow-left.png"), root_path, class: "back_btn" %>
    </div>
    <h4 class="text-white">New Transaction</h4>
  </div>

  <div class="mx-2">
    <%= form_with model: @expense do |form| %>
      <% if @expense.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>
          <ul>
            <% @expense.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="my-3 px-3">
        <%= form.text_field :name, placeholder: "Expense Name", require: true, class: 'w-100 bg-gray-100 p-2' %>
      </div>

      <div class="my-3 px-3">
        <%= form.number_field :amount, in: 1.0..1000.0, step: 0.5, placeholder: "Amount", require: true, class: 'w-100 bg-gray-100 p-2' %>
      </div>

      <div class="my-3 px-3">
        <%= form.collection_select :category_id, @categories, :id, :name, prompt: true, require: true, class: 'w-100 bg-gray-100 p-2'  %>
      </div>

      <div class="form-group">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous" />

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
 
    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">

    <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation" >
        <span class="navbar-toggler-icon"></span>
    </button>
        
    <div class="collapse navbar-collapse" id="navbarTogglerDemo0">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="#" >Account Settings</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Merchants</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Claim Promo</a></li>
        </ul>        
    </div>
</nav>

app/views/splashes/index.html.erb
<section class="conatainer splash">
    <div class="mb-5 rounded">
        <h1 class="display-1 title fw-bold fst-italic text-center mb-5">
           <span class="rounded-circle main-color p-5">Sen</span>
        </h1>
        <div class="mt-5">
          <%= link_to "LOG IN", new_user_session_path, class: "btn btn-light w-100 mt-2 mb-2 p-3" %>
          <%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-light w-100 mt-2 mb-2 p-3" %>
        </div>
    </div>
</section>